### ISSUE TITLE
Source IP address

### ISSUE THREAD

**Issue by mugzy** [duosecurity/duo_openvpn_as#2]
We are using Duo with OpenVPN Access Server and have found that the source IP (access device in the log) is not always recorded correctly.

Sometimes the "access device" IP shows up correctly, but other times it shows up as 127.0.0.1.

**Comment by DuoKristina** [comment]
Duo reports the IP address as passed to it by the OpenVPN AS server. If you have "Service Forwarding" enabled on your OpenVPN AS server (under "Server Network Settings"), it will appear to Duo that client connections are coming from the local host 127.0.0.1. Disable this setting and the client's IP will be used.

Thanks for using Duo!

**Comment by BradleyHiggins** [comment]
The Duo plugin can only report the IP address as passed to it by OpenVPN Access Server.  Unfortunately, we've found that OpenVPN AS will sometimes pass the loopback IP as the client's IP to plugins.  As DuoKristina mentioned, we know that it sends loopback when "Service Forwarding" is enabled, for example.  You'll need to open a support ticket with OpenVPN AS to determine the root cause of this issue.

To demonstrate that the Duo plugin is getting '127.0.0.1' from OpenVPN AS, you can modify the plugin source to log the IP address:


o Edit /usr/local/openvpn_as/scripts/duo_openvpn_as.py
o Find `def post_auth_cr(authcred, attributes, authret, info, crstate):` in the file
o In that function, find the line that reads: `ipaddr = authcred['client_ip_addr']`
o After that line, include a new line that says `log('Authenticating with authcred: {0}'.format(authcred))`
It should now look like this:

```python
def post_auth_cr(authcred, attributes, authret, info, crstate):
     # Don't do challenge/response on sessions or autologin clients.
     # autologin client: a client that has been issued a special
     #   certificate allowing authentication with only a certificate
     #   (used for unattended clients such as servers).
     # session: a client that has already authenticated and received
     #   a session token.  The client is attempting to authenticate
     #   again using the session token.
 
     if info.get('auth_method') in ('session', 'autologin'):
         return authret
 
     if SKIP_DUO_ON_VPN_AUTH and attributes.get('vpn_auth'):
         return authret
 
     username = authcred['username']
     ipaddr = authcred['client_ip_addr']
     log('Authenticating with authcred: {0}'.format(authcred))
 
     if crstate.get('challenge'):
```
o In order for openvpn_as to use this change, it needs to be registered. Run the command `/usr/local/openvpn_as/scripts/sacli -k auth.module.post_auth_script --value_file=/usr/local/openvpn_as/scripts/duo_openvpn_as.py ConfigPut`
o Restart openvpn_as, so that it starts running the new code: `/etc/init.d/openvpnas restart`
o Get the logs from /var/log/syslog after running an authentication.

You'll notice that OpenVPN AS is sending the loopback IP as the 'client_ip_addr' to the plugin:
> Jul  6 09:08:50 OVPNAS20 openvpnas: Duo OpenVPN_AS: Authenticating with authcred: {'username': 'brad', 'client_ip_addr': '127.0.0.1'}

You can then open a ticket with OpenVPN AS support, and ask them for further assistance.

Thanks for using Duo!
